### ISSUE TITLE
Position issue with Svelte

### ISSUE THREAD

**Issue by Blue-Nomad** [ovniroto/confettis#15]
Hi, I'm using your example code for the Drop & Party effects and the X and Y values don't seem to be respected. No matter what I do, the animation begins in the centre of the screen, so with Drop, all the confetti falls in a line from the centre.

The canvas is filling the screen as intended.

**Comment by Blue-Nomad** [comment]
See https://svelte-omnisite.vercel.app/playground/hello-world?version=5.0.0-next.272#H4sIAAAAAAAAE3WTQW_bMAyF_wqhi-1OdRUMAzqhKTCgQNHDdumx7kFVmFWYTWkSHSQI8t8HOW1qu5kvht7jJ4l89l6sXYtJ6Ke94F1AoQdBSEGmy6sfIdRpgy1n7cUkPKdbT4zESWhxk2x0gW9dF3xkuACTwHpaI7ODdfQdFO_LVDTUcEPWU2LoHN1FHx6taRGWoOpvJ8dsp851QzPqPpqN493gfp1xY-8z-RgQV2e5D2dE2YiGMduwhLKC5S3sGwKAU5P1saR8k_Oz1RANrXz3q-9eMJZKwqKSH_5Og6qVUouRZn1PrGEs_T42MttsOgE563p8DDv7J83oy4WEhVJqXJfyoM-fMmQgJ4lMyDyy_5DZkpPZjskVWjOM4bua7BfRrDRMtFcTMGl4giL97U3EQkKBbetCwgKej4WHqqFDTi0hPxBj3Ji2nMZ1CrLMtRKuVZWBdU-WnadPTQx3r97xiNxHgp-GX-tjZVnBBZSd2cJl_rYq-JJfwzVurt5-ioaEFIxbFppjj4fnwz9daIbagAMAAA==

**Comment by ovniroto** [comment]
I will check it out. Thank you for reporting it.

**Comment by ovniroto** [comment]
Fixed in version 0.3.6.
