### ISSUE TITLE
If you specify 'canvas' but the script can't find it, it adds loads of canvas elements

### ISSUE THREAD

**Issue by Blue-Nomad** [ovniroto/confettis#16]
See https://svelte-omnisite.vercel.app/playground/hello-world?version=5.0.0-next.272#H4sIAAAAAAAAE3VTTWvcMBD9K4MutlPF1VIKqcgGAoXSQ3vJMc5B0c42IvZIlcbLLsv-9yKbbG1nYx2M3oekmScdxda1mIR-PAo-BBR6AIQUZLo8uw-hTjtsOWPPJuEl3HpiJE5Ci9tkowt815Drgo8MV2ASWE9bZHawjb6D4m2aioYabsh6Sgydo-_RhwdrWoQ1qPrrmTH7OXPT0ML1I5qd48PAfln4ptx750NA3Fz0_WcmLhvRMGYa1lBWsL6DY0MAcC6yHiXlcShuGNbQziQNBWPiQo76_O01REMb3_3uu2eMpZKwqib8QYOqlVKrCWZ9T6xhCv0ZK1wsNm-NXLRjug07-5oW7uuVhJVSaqpLOYHLuwzhyFlUM2fu5QfOTMlZ06fODVoztOGbmq0X0Ww0zLAXEzBpeIQi_e1NxEJCgW3rQsICnkbhqWrolONMyD-JMe5MW85zPCdcZq2EG1Vlw7Yny87TuyKGs1dv9ojcR4Jfhl_qUVlWcAVlZ_ZwnS9dBZ_ybzjG7efzexFSMO5ZaI49np5O_wAcKFNJmwMAAA==

**Comment by ovniroto** [comment]
Fixed in version 0.3.6.
